baseURL = "https://nakibrayan.com"
theme = "custom"

defaultContentLanguage = "ar"
defaultContentLanguageInSubdir = true

[languages]
  [languages.ar]
    disabled = false
    languageCode = "ar"
    languageDirection = "rtl"
    languageName = "العربية"
    title = "موقع ريان نقيب"
    copyright = "CC BY-NC-SA 4.0"
    weight = 0

    [languages.ar.menus]
      [[languages.ar.menus.main]]
        name = 'المدوّنة المصغرة'
        pageRef = '/microblog'
        weight = 1
      [[languages.ar.menus.main]]
        name = 'المدوّنة'
        pageRef = '/blog'
        weight = 2
      [[languages.ar.menus.main]]
        name = 'الآن'
        pageRef = '/now'
        weight = 3
      [[languages.ar.menus.main]]
        name = 'يستخدم'
        pageRef = '/uses'
        weight = 4
      [[languages.ar.menus.main]]
        name = 'مكتبتي الشخصية'
        pageRef = '/personal_library'
        weight = 5
      [[languages.ar.menus.main]]
        name = 'مدوّنات أخرى'
        pageRef = '/blogroll'
        weight = 6
      [[languages.ar.menus.main]]
        name = 'تواصل معي'
        pageRef = '/contact_me'
        weight = 7

      [[languages.ar.menus.footer]]
        name = 'CC BY-NC-SA 4.0'
        url = 'https://creativecommons.org/licenses/by-nc-sa/4.0'
        weight = 1

      [[languages.ar.menus.footer]]
        name = 'سياسة الخصوصيّة'
        pageRef = '/privacy_policy'
        weight = 2

      [[languages.ar.menus.footer]]
        name = 'إِخلاء المسؤولية'
        pageRef = '/disclaimer'
        weight = 3

      [[languages.ar.menus.footer]]
        name = 'اشترك'
        pageRef = '/subscribe'
        weight = 4

    [languages.ar.params]
      Logo = "/avatar.svg"
      Name = "ريان نقيب"
      Pronouns = "هو"
      Occupation = "طالب اتصالات"
      Location = "الجزائر"
      Description = "أنا نقيب ريان وهذا موقعو ومدونتي. يوجد الكثير هنا، اذا شكرا لزيارتك!"
      Bio = ""

  [languages.en]
    disabled = false
    languageCode = "en"
    languageDirection = "ltr"
    languageName = "English"
    title = "Rayan Nakib's Website"
    copyright = "CC BY-NC-SA 4.0"
    weight = 1

    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Microblog'
        pageRef = '/microblog'
        weight = 1
      [[languages.en.menus.main]]
        name = 'Blog'
        pageRef = '/blog'
        weight = 2
      [[languages.en.menus.main]]
        name = 'Now'
        pageRef = '/now'
        weight = 3
      [[languages.en.menus.main]]
        name = 'Uses'
        pageRef = '/uses'
        weight = 4
      [[languages.en.menus.main]]
        name = 'Personal Library'
        pageRef = '/personal_library'
        weight = 5
      [[languages.en.menus.main]]
        name = 'Blogroll'
        pageRef = '/blogroll'
        weight = 6
      [[languages.en.menus.main]]
        name = 'Contact me'
        pageRef = '/contact_me'
        weight = 7

      [[languages.en.menus.footer]]
        name = 'CC BY-NC-SA 4.0'
        url = 'https://creativecommons.org/licenses/by-nc-sa/4.0'
        weight = 1

      [[languages.en.menus.footer]]
        name = 'Privacy Policy'
        pageRef = '/privacy_policy'
        weight = 2

      [[languages.en.menus.footer]]
        name = 'Disclaimer'
        pageRef = '/disclaimer'
        weight = 3

      [[languages.en.menus.footer]]
        name = 'Subscribe'
        pageRef = '/subscribe'
        weight = 4

    [languages.en.params]
      Logo = "/avatar.svg"
      Name = "Rayan Nakib"
      Pronouns = "he/him"
      Occupation = "Telecommunications Student"
      Location = "Algeria"
      Description = "I am Rayan Nakib and this is my website and blog. There’s a lot here, so thanks for stopping by!"
      Bio = ""

[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[services]
  [services.rss]
    limit = -1

[taxonomies]
  tag = 'tags'

[markup]
  [markup.highlight]
    noClasses = false
